// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	watchlist "movie-api/features/watchlist"

	mock "github.com/stretchr/testify/mock"
)

// Data is an autogenerated mock type for the Data type
type Data struct {
	mock.Mock
}

// DeleteWatchlist provides a mock function with given fields: id
func (_m *Data) DeleteWatchlist(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertWatchlist provides a mock function with given fields: wlData
func (_m *Data) InsertWatchlist(wlData watchlist.WatchlistCore) error {
	ret := _m.Called(wlData)

	var r0 error
	if rf, ok := ret.Get(0).(func(watchlist.WatchlistCore) error); ok {
		r0 = rf(wlData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectWatchlist provides a mock function with given fields: account_id
func (_m *Data) SelectWatchlist(account_id int) ([]watchlist.WatchlistCore, error) {
	ret := _m.Called(account_id)

	var r0 []watchlist.WatchlistCore
	if rf, ok := ret.Get(0).(func(int) []watchlist.WatchlistCore); ok {
		r0 = rf(account_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]watchlist.WatchlistCore)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(account_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
