// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	transaction "movie-api/features/transaction"

	mock "github.com/stretchr/testify/mock"
)

// Data is an autogenerated mock type for the Data type
type Data struct {
	mock.Mock
}

// InsertTransaction provides a mock function with given fields: trxData
func (_m *Data) InsertTransaction(trxData transaction.TransactionCore) error {
	ret := _m.Called(trxData)

	var r0 error
	if rf, ok := ret.Get(0).(func(transaction.TransactionCore) error); ok {
		r0 = rf(trxData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectTransaction provides a mock function with given fields: accound_id
func (_m *Data) SelectTransaction(accound_id int) ([]transaction.TransactionCore, error) {
	ret := _m.Called(accound_id)

	var r0 []transaction.TransactionCore
	if rf, ok := ret.Get(0).(func(int) []transaction.TransactionCore); ok {
		r0 = rf(accound_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]transaction.TransactionCore)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(accound_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
