name: "Running Unit Test"
on:
  push:
    branches:
      - "master"

jobs:
  "unit-test":
    name: "unit test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.3
      - name: running unit test
        run: go test ./... -cover
