// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	paymentmethod "movie-api/features/paymentmethod"

	mock "github.com/stretchr/testify/mock"
)

// Data is an autogenerated mock type for the Data type
type Data struct {
	mock.Mock
}

// DeletePaymentmethod provides a mock function with given fields: id
func (_m *Data) DeletePaymentmethod(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertPaymentmethod provides a mock function with given fields: pmData
func (_m *Data) InsertPaymentmethod(pmData paymentmethod.PaymentmethodCore) error {
	ret := _m.Called(pmData)

	var r0 error
	if rf, ok := ret.Get(0).(func(paymentmethod.PaymentmethodCore) error); ok {
		r0 = rf(pmData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectPaymentmethod provides a mock function with given fields: id
func (_m *Data) SelectPaymentmethod(id int) (paymentmethod.PaymentmethodCore, error) {
	ret := _m.Called(id)

	var r0 paymentmethod.PaymentmethodCore
	if rf, ok := ret.Get(0).(func(int) paymentmethod.PaymentmethodCore); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(paymentmethod.PaymentmethodCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
